### ISSUE TITLE
MDA

### ISSUE THREAD

**Issue by etodd** [MakeSchool-Tutorials/Game-Design-Documents#1]
Another non-essential idea here... I think we could rework the "Game Design" section.

We could incorporate the [MDA framework](http://www.cs.northwestern.edu/~hunicke/MDA.pdf). TL;DR it's a game design theory explained nicely in this [Extra Credits episode](https://www.youtube.com/watch?v=uepAJ-rqJKA).

Maybe we don't have time for this in the schedule when we're writing GDDs, but I think we could probably just watch that video and be done with it.

So instead of this structure:
- Objective
- Gameplay mechanics
- Level design

We could do a structure like this:
- **Aesthetics** - pick 1-3 aesthetics to focus on from this list:
  - Sensation (Game as sense-pleasure): Player experience something completely unfamiliar.
  - Fantasy (Game as make-believe): Imaginary world.
  - Narrative (Game as drama): A story that drives the player keep coming back
  - Challenge (Game as obstacle course): Urge to master something. Boosts a game's replay.
  - Fellowship (Game as social framework): A community where the player is an active part of it. Almost exclusive for interactive multiplayer games.
  - Discovery (Game as uncharted territory): Urge to explore game world.
  - Expression (Game as self-discovery): Own creativity. For example, creating character resembling player's own avatar.
  - Submission (Game as pastime): Connection to the game, as a whole, despite of constraints.
- **Mechanics** - what mechanics will you use to accomplish your aesthetic goals?
- **Dynamics** - what dynamics do you hope will arise from these mechanics, and how will they contribute to your aesthetic targets?

I don't think we need to get super deep into this. Honestly I don't know much about it. But I think it could help people think about games in a new light.

**Comment by dionlarson** [comment]
Added in 6dacf02.
